baseurl = "https://helm.sh/"
languageCode = "zh-cn"
theme = "docsy" # helm

contentDir = "content"
publishdir = "app"

canonifyURLs = "false"
pluralizeListTitles = "false"
plainIdAnchors = "true"
disableKinds = ["taxonomy", "taxonomyTerm"]

[markup]
[markup.goldmark]
[markup.goldmark.extensions]
typographer = false
[markup.highlight]
style = "manni"
guessSyntax = true

[Permalinks]
code = "/:filename/"

[params]
title = "Helm"
description = "Helm - The Kubernetes Package Manager."
googleAnalyticsId = "UA-42867143-2"
googleSiteVerification = "dCa3wS47cErhx0IpaxbB85NfcOP-vFxevknVk6fzf5I"
twittersite = "helmpack"
twittertype = "summary"
twitterimage = "img/og-image.png"
jsFiles = [
  "foundation",
  "foundation.accordion",
  "foundation.dropdown",
  "foundation.offcanvas",
  "foundation.slider",
  "foundation.tooltip",
  "modernizr",
  "clipboard.min",
  "app"
]

[[params.versions]]
version = "v3.2.4"
patch = "stable"
url = "https://helm.sh/docs"
primary = true

[[params.versions]]
version = "v2.16.9"
url = "https://v2.helm.sh/docs"

[[params.quicklinks]]
title = "快速链接"
description = "如何安装并开始使用Helm包括发行版，常见问题解答，和插件的说明。"
url = "/docs/intro/quickstart"

[[params.quicklinks]]
title = "图表向导"
description = "建设 Helm 实际步骤图表，如何结构，标志，和同步你的图表。"
url = "/docs/topics/charts"

[[params.quicklinks]]
title = "Video: 简介 Helm"
description = "观看马特·法里纳和Josh Dolitsky出席KubeCon 2019介绍了Helm。"
url = "https://www.youtube.com/watch?v=Zzwq9FmZdsU"

[[params.quicklinks]]
title = "从 V2 迁移到 V3"
description = "下面我们就如何从 Helm V2 到 Helm V3 迁移的博客文章。"
url = "/blog/migrate-from-helm-v2-to-helm-v3/"

[[params.quicklinks]]
title = "Helm 安全审计"
description = "Helm进行了审计和认为CNCF资助的第三方安全审计期间建议对公共部署。"
url = "/blog/2019-11-04-helm-security-audit-results/"

# Multilingual configuration
defaultContentLanguage = "zh"
disableLanguages = ["ko"]

# English
[languages.en]
title = "Helm"
description = "Helm - The Kubernetes Package Manager."
contentDir = "content/en"
languageName = "English"
weight = 1

[[languages.en.menus.main]]
name = "Home"
url = "/"
weight = 1

[[languages.en.menus.main]]
name = "Docs"
url = "/docs"
weight = 2

[[languages.en.menus.main]]
name = "Charts"
url = "https://hub.helm.sh/"
weight = 3

[[languages.en.menus.main]]
name = "Blog"
url = "/blog"
weight = 4

[[languages.en.menus.main]]
name = "Community"
url = "https://github.com/helm/community"
weight = 5

# Chinese
[languages.zh]
title = "Helm"
description = "Helm - 该Kubernetes包管理器。"
contentDir = "content/zh"
languageName = "中文 Chinese"
weight = 1

# [[languages.zh.menus.main]]
# name = "主页"
# url = "/"
# weight = 1

[[languages.zh.menus.main]]
name = "文档"
url = "/docs"
weight = 2

[[languages.zh.menus.main]]
name = "博客"
url = "/blog"
weight = 3

[[languages.zh.menus.main]]
name = "图表"
url = "https://hub.helm.sh/"
weight = 4
external = "yes"

[[languages.zh.menus.main]]
name = "社区"
url = "https://github.com/helm/community"
weight = 5

[languages.zh.params]
language_alternatives = ["en"]
